# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - "nightly"
    - 3.6
    - 3.5
    - 3.4
    - 3.3
    - 2.7
    - pypy
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    - 'if [[ $GROUP != js* ]]; then COVERAGE=""; fi'
install:
    - |
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
        pip install 'pip<18' --upgrade
      else
        pip install pip --upgrade
      fi
    - pip install pip --upgrade
    - pip install "setuptools>=18.5" 
    # Installs PyPy (+ its Numpy). Based on @frol comment at:
    # https://github.com/travis-ci/travis-ci/issues/5027
    - |
        if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
          export PYENV_ROOT="$HOME/.pyenv"
          if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
            cd "$PYENV_ROOT" && git pull
          else
            rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
          fi
          export PYPY_VERSION="5.3.1"
          "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
          virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
          source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
          pip install https://bitbucket.org/pypy/numpy/get/master.zip
        fi
    - pip install -f travis-wheels/wheelhouse -e file://$PWD#egg=ipython[test]
    - pip install codecov mock
script:
    - cd /tmp && iptest --coverage xml && cd -
after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - codecov

matrix:
    allow_failures:
        - python: nightly
        - python: pypy
